version: '3.8'

services:
  kindle-online:
    build: .
    container_name: kindle-online
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./storage:/app/storage
    restart: unless-stopped
